### PR TITLE
74749 Erp Facade Initial Project Skeleton

### PR DESCRIPTION
**Pull request by Shirin14926**
ERP Facade API Project Skeleton

### CODE REVIEW

**Comment by jrippington** [comment]
Can we please add all of the functional projects to the 'src' subdirectory, and all test-related projects to the 'tests' subdirectory as indicated in the initial commit? Thanks!

**Review by jrippington — CHANGES_REQUESTED** [review]
Can we please add all functional projects to the 'src' subdirectory, and all test-related projects to the 'tests' subdirectory as indicated in the initial commit. Thanks!

**Comment by Shirin14926** [comment]
> Can we please add all of the functional projects to the 'src' subdirectory, and all test-related projects to the 'tests' subdirectory as indicated in the initial commit? Thanks!

Added src and tests folders

**Comment by Shirin14926** [comment]
> > Can we please add all of the functional projects to the 'src' subdirectory, and all test-related projects to the 'tests' subdirectory as indicated in the initial commit? Thanks!
> 
> Added src and tests folders

**Review by jrippington — CHANGES_REQUESTED** [review]
Looks good! Just need to move ERPFacade.Common into the src directory please!

**Review by jrippington — APPROVED** [review]
Looks good!

**Review by JiviteshT — APPROVED** [review]
Looks good.

**Pull request merged**
