### PR TITLE
83728 new rule added for product name for ENC cell actions

### PR DESCRIPTION
**Pull request by pravinvarade10801**
1. New rule implementation for product name
2. Unit test added
3. FT's added
4. Commented code in yml file for QA deploy
5. Removed category tags from all FTs
6. Removed 1 FT from UnitOfSaleScenario related 403
7. Renamed ENC event json attributes “contentChanged” to “contentChange” and “'providerDesc” to “'providerName”

### CODE REVIEW

**Review by harshal11869 — APPROVED** [review]
Looks Good

**Review by Sadha1501493 — APPROVED** [review]
Please update mapping excel for webhook scenario#33-36.
Rest all looks good.

**Review by RaviK2233 — APPROVED** [review]
Reviewed FT and looks good

**Review by jrippington — APPROVED** [review]
Looks good to me

**Review by JiviteshT — APPROVED** [review]
Looks good

**Pull request merged**
