### PR TITLE
Dev s100/feature/185615 add key based configuration and authentication

### PR DESCRIPTION
**Pull request by prasad14878**
This PR contains code changes, unit test cases
Please review the same.

Thanks

### CODE REVIEW

**Review by gaurav15233 — APPROVED** [review]
LGTM

**Review by gaurav15233 — APPROVED** [review]
LGTM, Just a minor suggestion Please change method name S100ErpFacadeCallBack to S100SapCallBack

**Review by jagannathsankpal — APPROVED** [review]
LGTM

**Review by gaurav15233 — APPROVED** [review]
LGTM

**Review by JiviteshT — APPROVED** [review]
Looks good

**Review by jrippington — APPROVED** [review]
Looks good, thanks

**Pull request merged**
