### PR TITLE
77888 - scenario implementation move enc cell change in uos

### PR DESCRIPTION
**Pull request by pravinvarade10801**
1. Action rules added in SapAction.json 
2. XML payload generated using Sap action rules in SapMessageBuilder
3. Removed unused files
4. Added unit test
5. Added FTs

### CODE REVIEW

**Review by Sadha1501493 — COMMENTED** [review]
@prashantmgupta : LGTM. Just add JSON file mapping Excel as well under FT-->Data folder

**Review by Sadha1501493 — APPROVED** [review]

**Review by harshal11869 — APPROVED** [review]
LGTM

**Review by jrippington — APPROVED** [review]
Looks good to me, thanks!

**Review by jrippington — APPROVED** [review]
Looks good to me, thanks!

**Review by martyn-fewtrell — APPROVED** [review]
Looks good

**Pull request merged**
