### PR TITLE
Dev s100/feature/182707 implement product actions with s100xmltransformer

### PR DESCRIPTION
**Pull request by ajay15273**
Hi,
 
Dependency :- no dependency
 
This PR contains code changes, unit tests and functional tests of implement product actions with s100xmltransformer.
Please review.
 
Regards!

### CODE REVIEW

**Review by gaurav15233 — APPROVED** [review]
LGTM

**Review by Vishal14583 — APPROVED** [review]
LGTM

**Review by jagannathsankpal — APPROVED** [review]
LGTM

**Review by jrippington — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
